import './App.css'; // Optional: for custom styling

// Mock data for states in India
const mockStates = [
  { id: 1, name: 'Maharashtra' },
  { id: 2, name: 'Goa' },
  { id: 3, name: 'Karnataka' },
  { id: 4, name: 'Haryana' },
  { id: 5, name: 'Himachal Pradesh' },
  { id: 6, name: 'Jammu and Kashmir' },
  { id: 7, name: 'Tamil Nadu' },
  { id: 8, name: 'Delhi' },
  { id: 9, name: 'West Bengal' },
  { id: 10, name: 'Uttar Pradesh' },
  { id: 11, name: 'Gujarat' },
  { id: 12, name: 'Rajasthan' },
  { id: 13, name: 'Madhya Pradesh' },
  { id: 14, name: 'Telangana' },
  { id: 15, name: 'Andhra Pradesh' },
  { id: 16, name: 'Bihar' },
  { id: 17, name: 'Odisha' },
  { id: 18, name: 'Kerala' },
  { id: 19, name: 'Punjab' },
  { id: 20, name: 'Chhattisgarh' },
];

// Mock data for hotels in each state
const mockHotels = {
  1: [
    { id: 1, name: 'The Taj Mahal Palace', address: 'Mumbai, Maharashtra' },
    { id: 2, name: 'The Leela', address: 'Mumbai, Maharashtra' },
    { id: 3, name: 'JW Marriott', address: 'Mumbai, Maharashtra' },
    { id: 4, name: 'ITC Grand Central', address: 'Mumbai, Maharashtra' },
    { id: 5, name: 'Radisson Blu', address: 'Navi Mumbai, Maharashtra' },
    { id: 6, name: 'Hotel Marine Plaza', address: 'Mumbai, Maharashtra' },
    { id: 7, name: 'Trident Nariman Point', address: 'Mumbai, Maharashtra' },
    { id: 8, name: 'Novotel Mumbai Juhu Beach', address: 'Mumbai, Maharashtra' },
    { id: 9, name: 'Taj Lands End', address: 'Mumbai, Maharashtra' },
    { id: 10, name: 'Sofitel Mumbai BKC', address: 'Mumbai, Maharashtra' },
  ],
  2: [
    { id: 1, name: 'W Goa', address: 'Vagator, Goa' },
    { id: 2, name: 'Radisson Blu Resort', address: 'Cavelossim, Goa' },
    { id: 3, name: 'Heritage Village Resort & Spa', address: 'Goin, Goa' },
    { id: 4, name: 'Taj Exotica Resort & Spa', address: 'Benaulim, Goa' },
    { id: 5, name: 'The Leela Goa', address: 'Cavelossim, Goa' },
    { id: 6, name: 'Grand Hyatt Goa', address: 'Bambolim, Goa' },
    { id: 7, name: 'Alila Diwa Goa', address: 'Majorda, Goa' },
    { id: 8, name: 'Taj Fort Aguada Resort & Spa', address: 'Sinquerim, Goa' },
    { id: 9, name: 'The Lalit Golf & Spa Resort', address: 'Canacona, Goa' },
    { id: 10, name: 'Caravela Beach Resort', address: 'Varca, Goa' },
  ],
  3: [
    { id: 1, name: 'The Leela Palace', address: 'Bangalore, Karnataka' },
    { id: 2, name: 'Taj West End', address: 'Bangalore, Karnataka' },
    { id: 3, name: 'JW Marriott', address: 'Bangalore, Karnataka' },
    { id: 4, name: 'ITC Gardenia', address: 'Bangalore, Karnataka' },
    { id: 5, name: 'Radisson Blu', address: 'Bangalore, Karnataka' },
    { id: 6, name: 'Shangri-La Hotel', address: 'Bangalore, Karnataka' },
    { id: 7, name: 'Vivanta by Taj', address: 'Bangalore, Karnataka' },
    { id: 8, name: 'The Chancery Pavilion', address: 'Bangalore, Karnataka' },
    { id: 9, name: 'The Oberoi', address: 'Bangalore, Karnataka' },
    { id: 10, name: 'The Paul', address: 'Bangalore, Karnataka' },
  ],
  4: [
    { id: 1, name: 'The Westin Sohna Resort & Spa', address: 'Sohna, Haryana' },
    { id: 2, name: 'Taj Hotel & Convention Centre', address: 'Gurugram, Haryana' },
    { id: 3, name: 'Radisson Gurugram', address: 'Gurugram, Haryana' },
    { id: 4, name: 'ITC Grand Bharat', address: 'Gurugram, Haryana' },
    { id: 5, name: 'Trident, Gurgaon', address: 'Gurugram, Haryana' },
    { id: 6, name: 'The Oberoi', address: 'Gurugram, Haryana' },
    { id: 7, name: 'Lemon Tree Hotel', address: 'Gurugram, Haryana' },
    { id: 8, name: 'Holiday Inn', address: 'Gurugram, Haryana' },
    { id: 9, name: 'Hyatt Regency', address: 'Gurugram, Haryana' },
    { id: 10, name: 'Country Inn & Suites', address: 'Gurugram, Haryana' },
  ],
  5: [
    { id: 1, name: 'The Oberoi Cecil', address: 'Shimla, Himachal Pradesh' },
    { id: 2, name: 'Wildflower Hall', address: 'Mashobra, Himachal Pradesh' },
    { id: 3, name: 'Radisson Hotel', address: 'Shimla, Himachal Pradesh' },
    { id: 4, name: 'Taj Theog Resort & Spa', address: 'Theog, Himachal Pradesh' },
    { id: 5, name: 'The Chalets Naldehra', address: 'Naldehra, Himachal Pradesh' },
    { id: 6, name: 'Sukhdev Vihar', address: 'Shimla, Himachal Pradesh' },
    { id: 7, name: 'Royal Castle', address: 'Shimla, Himachal Pradesh' },
    { id: 8, name: 'Hotel Combermere', address: 'Shimla, Himachal Pradesh' },
    { id: 9, name: 'Hotel Hilltop', address: 'Shimla, Himachal Pradesh' },
    { id: 10, name: 'Shivalik River Retreat', address: 'Kullu, Himachal Pradesh' },
  ],
  6: [
    { id: 1, name: 'Hotel Hilltop', address: 'Pahalgam, Jammu and Kashmir' },
    { id: 2, name: 'Khyber Himalayan Resort & Spa', address: 'Gulmarg, Jammu and Kashmir' },
    { id: 3, name: 'Taj Vivanta', address: 'Srinagar, Jammu and Kashmir' },
    { id: 4, name: 'Hotel Grand Mumtaz', address: 'Srinagar, Jammu and Kashmir' },
    { id: 5, name: 'Hotel Hilltop', address: 'Pahalgam, Jammu and Kashmir' },
    { id: 6, name: 'The Lalit Grand Palace', address: 'Srinagar, Jammu and Kashmir' },
    { id: 7, name: 'Hotel New Mamta', address: 'Srinagar, Jammu and Kashmir' },
    { id: 8, name: 'Hotel Srinagar', address: 'Srinagar, Jammu and Kashmir' },
    { id: 9, name: 'Hotel Shahenshah', address: 'Srinagar, Jammu and Kashmir' },
    { id: 10, name: 'Hotel Royal Castle', address: 'Srinagar, Jammu and Kashmir' },
  ],
  7: [
    { id: 1, name: 'The Leela Palace', address: 'Chennai, Tamil Nadu' },
    { id: 2, name: 'Taj Coromandel', address: 'Chennai, Tamil Nadu' },
    { id: 3, name: 'JW Marriott', address: 'Chennai, Tamil Nadu' },
    { id: 4, name: 'The Park', address: 'Chennai, Tamil Nadu' },
    { id: 5, name: 'ITC Grand Chola', address: 'Chennai, Tamil Nadu' },
    { id: 6, name: 'Radisson Blu', address: 'Chennai, Tamil Nadu' },
    { id: 7, name: 'Taj Connemara', address: 'Chennai, Tamil Nadu' },
    { id: 8, name: 'Hyatt Regency', address: 'Chennai, Tamil Nadu' },
    { id: 9, name: 'The Raintree Hotel', address: 'Chennai, Tamil Nadu' },
    { id: 10, name: 'The Westin Chennai Velachery', address: 'Chennai, Tamil Nadu' },
  ],
  8: [
    { id: 1, name: 'The Imperial', address: 'Delhi' },
    { id: 2, name: 'Taj Mahal Hotel', address: 'Delhi' },
    { id: 3, name: 'ITC Maurya', address: 'Delhi' },
    { id: 4, name: 'The Oberoi', address: 'Delhi' },
    { id: 5, name: 'Shangri-La Eros Hotel', address: 'Delhi' },
    { id: 6, name: 'Hyatt Regency', address: 'Delhi' },
    { id: 7, name: 'The Park', address: 'Delhi' },
    { id: 8, name: 'Leela Palace', address: 'Delhi' },
    { id: 9, name: 'Radisson Blu', address: 'Delhi' },
    { id: 10, name: 'Holiday Inn', address: 'Delhi' },
  ],
  9: [
    { id: 1, name: 'The Oberoi Grand', address: 'Kolkata, West Bengal' },
    { id: 2, name: 'Taj Bengal', address: 'Kolkata, West Bengal' },
    { id: 3, name: 'ITC Sonar', address: 'Kolkata, West Bengal' },
    { id: 4, name: 'The Westin', address: 'Kolkata, West Bengal' },
    { id: 5, name: 'JW Marriott', address: 'Kolkata, West Bengal' },
    { id: 6, name: 'Hyatt Regency', address: 'Kolkata, West Bengal' },
    { id: 7, name: 'The Lalit Great Eastern', address: 'Kolkata, West Bengal' },
    { id: 8, name: 'Novotel', address: 'Kolkata, West Bengal' },
    { id: 9, name: 'The Park', address: 'Kolkata, West Bengal' },
    { id: 10, name: 'Radisson Kolkata', address: 'Kolkata, West Bengal' },
  ],
  10: [
    { id: 1, name: 'Taj GVK', address: 'Hyderabad, Telangana' },
    { id: 2, name: 'JW Marriott', address: 'Hyderabad, Telangana' },
    { id: 3, name: 'ITC Kohenur', address: 'Hyderabad, Telangana' },
    { id: 4, name: 'Radisson Blu', address: 'Hyderabad, Telangana' },
    { id: 5, name: 'The Park', address: 'Hyderabad, Telangana' },
    { id: 6, name: 'Novotel', address: 'Hyderabad, Telangana' },
    { id: 7, name: 'Hyatt Place', address: 'Hyderabad, Telangana' },
    { id: 8, name: 'Sheraton Hyderabad', address: 'Hyderabad, Telangana' },
    { id: 9, name: 'The Westin', address: 'Hyderabad, Telangana' },
    { id: 10, name: 'The Hegdewar', address: 'Hyderabad, Telangana' },
  ],
  11: [
    { id: 1, name: 'The Leela', address: 'Ahmedabad, Gujarat' },
    { id: 2, name: 'Taj Skyline', address: 'Ahmedabad, Gujarat' },
    { id: 3, name: 'Hyatt Regency', address: 'Ahmedabad, Gujarat' },
    { id: 4, name: 'Radisson Blu', address: 'Ahmedabad, Gujarat' },
    { id: 5, name: 'Novotel', address: 'Ahmedabad, Gujarat' },
    { id: 6, name: 'Courtyard by Marriott', address: 'Ahmedabad, Gujarat' },
    { id: 7, name: 'The Fern', address: 'Ahmedabad, Gujarat' },
    { id: 8, name: 'Fortune Landmark', address: 'Ahmedabad, Gujarat' },
    { id: 9, name: 'The Grand Bhagwati', address: 'Ahmedabad, Gujarat' },
    { id: 10, name: 'Pride Plaza Hotel', address: 'Ahmedabad, Gujarat' },
  ],
  12: [
    { id: 1, name: 'Taj Aravali Resort', address: 'Udaipur, Rajasthan' },
    { id: 2, name: 'The Leela Palace', address: 'Udaipur, Rajasthan' },
    { id: 3, name: 'JW Marriott', address: 'Jaipur, Rajasthan' },
    { id: 4, name: 'Rambagh Palace', address: 'Jaipur, Rajasthan' },
    { id: 5, name: 'ITC Rajputana', address: 'Jaipur, Rajasthan' },
    { id: 6, name: 'Shree Ram Heritage', address: 'Jaipur, Rajasthan' },
    { id: 7, name: 'Hilton Jaipur', address: 'Jaipur, Rajasthan' },
    { id: 8, name: 'The Oberoi Rajvilas', address: 'Jaipur, Rajasthan' },
    { id: 9, name: 'Trident Jaipur', address: 'Jaipur, Rajasthan' },
    { id: 10, name: 'Taj Lake Palace', address: 'Udaipur, Rajasthan' },
  ],
  13: [
    { id: 1, name: 'Taj Lake Palace', address: 'Udaipur, Madhya Pradesh' },
    { id: 2, name: 'ITC Narmada', address: 'Indore, Madhya Pradesh' },
    { id: 3, name: 'Radisson Blu', address: 'Indore, Madhya Pradesh' },
    { id: 4, name: 'JW Marriott', address: 'Gwalior, Madhya Pradesh' },
    { id: 5, name: 'The Lalit', address: 'Khajuraho, Madhya Pradesh' },
    { id: 6, name: 'The Westin', address: 'Sagar, Madhya Pradesh' },
    { id: 7, name: 'Ramada', address: 'Bhopal, Madhya Pradesh' },
    { id: 8, name: 'Courtyard by Marriott', address: 'Indore, Madhya Pradesh' },
    { id: 9, name: 'Hotel Amar Vilas', address: 'Khajuraho, Madhya Pradesh' },
    { id: 10, name: 'Hotel Landmark', address: 'Bhopal, Madhya Pradesh' },
  ],
  14: [
    { id: 1, name: 'Taj Falaknuma Palace', address: 'Hyderabad, Telangana' },
    { id: 2, name: 'The Leela', address: 'Hyderabad, Telangana' },
    { id: 3, name: 'Radisson Blu', address: 'Hyderabad, Telangana' },
    { id: 4, name: 'ITC Kohenur', address: 'Hyderabad, Telangana' },
    { id: 5, name: 'JW Marriott', address: 'Hyderabad, Telangana' },
    { id: 6, name: 'Sheraton', address: 'Hyderabad, Telangana' },
    { id: 7, name: 'Novotel', address: 'Hyderabad, Telangana' },
    { id: 8, name: 'The Westin', address: 'Hyderabad, Telangana' },
    { id: 9, name: 'Taj Banjara', address: 'Hyderabad, Telangana' },
    { id: 10, name: 'Hyatt Place', address: 'Hyderabad, Telangana' },
  ],
  15: [
    { id: 1, name: 'The Leela', address: 'Visakhapatnam, Andhra Pradesh' },
    { id: 2, name: 'Novotel', address: 'Visakhapatnam, Andhra Pradesh' },
    { id: 3, name: 'Taj Residency', address: 'Visakhapatnam, Andhra Pradesh' },
    { id: 4, name: 'Radisson Blu', address: 'Vijayawada, Andhra Pradesh' },
    { id: 5, name: 'Hyatt', address: 'Vijayawada, Andhra Pradesh' },
    { id: 6, name: 'ITC Kakatiya', address: 'Vijayawada, Andhra Pradesh' },
    { id: 7, name: 'Taj Gateway', address: 'Vijayawada, Andhra Pradesh' },
    { id: 8, name: 'Courtyard by Marriott', address: 'Visakhapatnam, Andhra Pradesh' },
    { id: 9, name: 'Radisson', address: 'Visakhapatnam, Andhra Pradesh' },
    { id: 10, name: 'Green Park', address: 'Vijayawada, Andhra Pradesh' },
  ],
  16: [
    { id: 1, name: 'The Leela Palace', address: 'Chennai, Tamil Nadu' },
    { id: 2, name: 'JW Marriott', address: 'Chennai, Tamil Nadu' },
    { id: 3, name: 'Radisson Blu', address: 'Chennai, Tamil Nadu' },
    { id: 4, name: 'ITC Grand Chola', address: 'Chennai, Tamil Nadu' },
    { id: 5, name: 'The Park', address: 'Chennai, Tamil Nadu' },
    { id: 6, name: 'The Westin', address: 'Chennai, Tamil Nadu' },
    { id: 7, name: 'The Raintree', address: 'Chennai, Tamil Nadu' },
    { id: 8, name: 'Hyatt Regency', address: 'Chennai, Tamil Nadu' },
    { id: 9, name: 'The Taj Club House', address: 'Chennai, Tamil Nadu' },
    { id: 10, name: 'Taj Coromandel', address: 'Chennai, Tamil Nadu' },
  ],
  17: [
    { id: 1, name: 'The Taj Mahal Palace', address: 'Mumbai, Maharashtra' },
    { id: 2, name: 'ITC Maratha', address: 'Mumbai, Maharashtra' },
    { id: 3, name: 'JW Marriott', address: 'Mumbai, Maharashtra' },
    { id: 4, name: 'The Leela', address: 'Mumbai, Maharashtra' },
    { id: 5, name: 'Taj Lands End', address: 'Mumbai, Maharashtra' },
    { id: 6, name: 'Trident Nariman Point', address: 'Mumbai, Maharashtra' },
    { id: 7, name: 'Hyatt Regency', address: 'Mumbai, Maharashtra' },
    { id: 8, name: 'The Oberoi', address: 'Mumbai, Maharashtra' },
    { id: 9, name: 'Four Seasons Hotel', address: 'Mumbai, Maharashtra' },
    { id: 10, name: 'The St. Regis', address: 'Mumbai, Maharashtra' },
  ],
  18: [
    { id: 1, name: 'The Leela Palace', address: 'Bengaluru, Karnataka' },
    { id: 2, name: 'Taj West End', address: 'Bengaluru, Karnataka' },
    { id: 3, name: 'JW Marriott', address: 'Bengaluru, Karnataka' },
    { id: 4, name: 'ITC Gardenia', address: 'Bengaluru, Karnataka' },
    { id: 5, name: 'Radisson Blu', address: 'Bengaluru, Karnataka' },
    { id: 6, name: 'Hyatt Centric', address: 'Bengaluru, Karnataka' },
    { id: 7, name: 'Sheraton Grand', address: 'Bengaluru, Karnataka' },
    { id: 8, name: 'The Lalit Ashok', address: 'Bengaluru, Karnataka' },
    { id: 9, name: 'The Ritz-Carlton', address: 'Bengaluru, Karnataka' },
    { id: 10, name: 'Oakwood Residence', address: 'Bengaluru, Karnataka' },
  ],
  19: [
    { id: 1, name: 'Taj Exotica', address: 'Goa' },
    { id: 2, name: 'The Leela', address: 'Goa' },
    { id: 3, name: 'JW Marriott', address: 'Goa' },
    { id: 4, name: 'Radisson Blu', address: 'Goa' },
    { id: 5, name: 'W Goa', address: 'Goa' },
    { id: 6, name: 'Hyatt', address: 'Goa' },
    { id: 7, name: 'ITC Grand Goa', address: 'Goa' },
    { id: 8, name: 'Taj Fort Aguada', address: 'Goa' },
    { id: 9, name: 'Novotel', address: 'Goa' },
    { id: 10, name: 'Alila Diwa', address: 'Goa' },
  ],
  20: [
    { id: 1, name: 'Taj Yeshwantpur', address: 'Bengaluru, Karnataka' },
    { id: 2, name: 'Radisson Blu', address: 'Bengaluru, Karnataka' },
    { id: 3, name: 'ITC Gardenia', address: 'Bengaluru, Karnataka' },
    { id: 4, name: 'The Leela Palace', address: 'Bengaluru, Karnataka' },
    { id: 5, name: 'JW Marriott', address: 'Bengaluru, Karnataka' },
    { id: 6, name: 'Sheraton Grand', address: 'Bengaluru, Karnataka' },
    { id: 7, name: 'The Lalit Ashok', address: 'Bengaluru, Karnataka' },
    { id: 8, name: 'Hyatt Centric', address: 'Bengaluru, Karnataka' },
    { id: 9, name: 'Taj West End', address: 'Bengaluru, Karnataka' },
    { id: 10, name: 'Oakwood Residence', address: 'Bengaluru, Karnataka' },
  ],
  21: [
    { id: 1, name: 'Taj Lake Palace', address: 'Udaipur, Rajasthan' },
    { id: 2, name: 'The Leela', address: 'Udaipur, Rajasthan' },
    { id: 3, name: 'JW Marriott', address: 'Jaipur, Rajasthan' },
    { id: 4, name: 'ITC Rajputana', address: 'Jaipur, Rajasthan' },
    { id: 5, name: 'Rambagh Palace', address: 'Jaipur, Rajasthan' },
    { id: 6, name: 'Hilton Jaipur', address: 'Jaipur, Rajasthan' },
    { id: 7, name: 'The Oberoi Rajvilas', address: 'Jaipur, Rajasthan' },
    { id: 8, name: 'Trident Jaipur', address: 'Jaipur, Rajasthan' },
    { id: 9, name: 'Taj Aravali Resort', address: 'Udaipur, Rajasthan' },
    { id: 10, name: 'JW Marriott', address: 'Jaipur, Rajasthan' },
  ],
  22: [
    { id: 1, name: 'The Imperial', address: 'Delhi' },
    { id: 2, name: 'Taj Mahal Hotel', address: 'Delhi' },
    { id: 3, name: 'ITC Maurya', address: 'Delhi' },
    { id: 4, name: 'The Oberoi', address: 'Delhi' },
    { id: 5, name: 'Shangri-La Eros Hotel', address: 'Delhi' },
    { id: 6, name: 'Hyatt Regency', address: 'Delhi' },
    { id: 7, name: 'The Park', address: 'Delhi' },
    { id: 8, name: 'Leela Palace', address: 'Delhi' },
    { id: 9, name: 'Radisson Blu', address: 'Delhi' },
    { id: 10, name: 'Holiday Inn', address: 'Delhi' },
  ],
  23: [
    { id: 1, name: 'The Oberoi Grand', address: 'Kolkata, West Bengal' },
    { id: 2, name: 'Taj Bengal', address: 'Kolkata, West Bengal' },
    { id: 3, name: 'ITC Sonar', address: 'Kolkata, West Bengal' },
    { id: 4, name: 'The Westin', address: 'Kolkata, West Bengal' },
    { id: 5, name: 'JW Marriott', address: 'Kolkata, West Bengal' },
    { id: 6, name: 'Hyatt Regency', address: 'Kolkata, West Bengal' },
    { id: 7, name: 'The Lalit Great Eastern', address: 'Kolkata, West Bengal' },
    { id: 8, name: 'Novotel', address: 'Kolkata, West Bengal' },
    { id: 9, name: 'Radisson', address: 'Kolkata, West Bengal' },
    { id: 10, name: 'Taj City Centre New Town', address: 'Kolkata, West Bengal' },
  ],
  24: [
    { id: 1, name: 'The Taj Mahal Palace', address: 'Mumbai, Maharashtra' },
    { id: 2, name: 'ITC Maratha', address: 'Mumbai, Maharashtra' },
    { id: 3, name: 'JW Marriott', address: 'Mumbai, Maharashtra' },
    { id: 4, name: 'The Leela', address: 'Mumbai, Maharashtra' },
    { id: 5, name: 'Taj Lands End', address: 'Mumbai, Maharashtra' },
    { id: 6, name: 'Trident Nariman Point', address: 'Mumbai, Maharashtra' },
    { id: 7, name: 'Hyatt Regency', address: 'Mumbai, Maharashtra' },
    { id: 8, name: 'The Oberoi', address: 'Mumbai, Maharashtra' },
    { id: 9, name: 'Four Seasons Hotel', address: 'Mumbai, Maharashtra' },
    { id: 10, name: 'The St. Regis', address: 'Mumbai, Maharashtra' },
  ],
  25: [
    { id: 1, name: 'The Oberoi Udaivilas', address: 'Udaipur, Rajasthan' },
    { id: 2, name: 'The Leela Palace', address: 'Udaipur, Rajasthan' },
    { id: 3, name: 'JW Marriott', address: 'Jaipur, Rajasthan' },
    { id: 4, name: 'ITC Rajputana', address: 'Jaipur, Rajasthan' },
    { id: 5, name: 'Rambagh Palace', address: 'Jaipur, Rajasthan' },
    { id: 6, name: 'Hilton Jaipur', address: 'Jaipur, Rajasthan' },
    { id: 7, name: 'The Oberoi Rajvilas', address: 'Jaipur, Rajasthan' },
    { id: 8, name: 'Trident Jaipur', address: 'Jaipur, Rajasthan' },
    { id: 9, name: 'Taj Aravali Resort', address: 'Udaipur, Rajasthan' },
    { id: 10, name: 'JW Marriott', address: 'Jaipur, Rajasthan' },
  ],
  26: [
    { id: 1, name: 'The Taj Mahal Palace', address: 'Mumbai, Maharashtra' },
    { id: 2, name: 'ITC Maratha', address: 'Mumbai, Maharashtra' },
    { id: 3, name: 'JW Marriott', address: 'Mumbai, Maharashtra' },
    { id: 4, name: 'The Leela', address: 'Mumbai, Maharashtra' },
    { id: 5, name: 'Taj Lands End', address: 'Mumbai, Maharashtra' },
    { id: 6, name: 'Trident Nariman Point', address: 'Mumbai, Maharashtra' },
    { id: 7, name: 'Hyatt Regency', address: 'Mumbai, Maharashtra' },
    { id: 8, name: 'The Oberoi', address: 'Mumbai, Maharashtra' },
    { id: 9, name: 'Four Seasons Hotel', address: 'Mumbai, Maharashtra' },
    { id: 10, name: 'The St. Regis', address: 'Mumbai, Maharashtra' },
  ],
  27: [
    { id: 1, name: 'The Oberoi Udaivilas', address: 'Udaipur, Rajasthan' },
    { id: 2, name: 'The Leela Palace', address: 'Udaipur, Rajasthan' },
    { id: 3, name: 'JW Marriott', address: 'Jaipur, Rajasthan' },
    { id: 4, name: 'ITC Rajputana', address: 'Jaipur, Rajasthan' },
    { id: 5, name: 'Rambagh Palace', address: 'Jaipur, Rajasthan' },
    { id: 6, name: 'Hilton Jaipur', address: 'Jaipur, Rajasthan'  },
    { id: 7, name: 'The Oberoi Rajvilas', address: 'Jaipur, Rajasthan' },
    { id: 8, name: 'Trident Jaipur', address: 'Jaipur, Rajasthan' },
    { id: 9, name: 'Taj Aravali Resort', address: 'Udaipur, Rajasthan' },
    { id: 10, name: 'JW Marriott', address: 'Jaipur, Rajasthan' },
  ],
};

export default hotelsData;
